[workspace]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "nbody"
platforms = ["linux-64"]
version = "0.1.0"

[feature.cuda]
system-requirements = { cuda = "12" }
channels = ["nvidia"]

[dependencies]
python = "==3.12"
numpy = ">=2.3.2,<3"
pygame = ">=2.6.1,<3"
max = "*"  # includes `mojo-compiler`
mojo = "*" # includes lsp, debugger, formatter etc.
moderngl = ">=5.11.1,<6"
moderngl-window = ">=3.1.1,<4"
scalene = ">=1.5.51,<2"

[environments]
cuda = { features = ["cuda"], solve-group = "cuda" }
default = { features = ["cuda"] }

[tasks]

nbody_cpu = "python nbody.py --cpu"
nbody_mojo_gpu = "mojo package ./op -o ./op/op.mojopkg && python nbody.py --mojo_gpu"
nbody_mojo_gpu_opt = "mojo package ./op -o ./op/op.mojopkg && python nbody.py --mojo_opt_gpu"
nbody_mojo_cpu = "mojo package ./op -o ./op/op.mojopkg && python nbody.py --mojo_cpu"

bench_nbody_cpu = "python bench.py --cpu"
bench_nbody_mojo_gpu = "mojo package ./op -o ./op/op.mojopkg && python bench.py --mojo_gpu"
bench_nbody_mojo_cpu = "mojo package ./op -o ./op/op.mojopkg && python bench.py --mojo_cpu"
bench_nbody_mojo_gpu_opt = "mojo package ./op -o ./op/op.mojopkg && python bench.py --mojo_opt_gpu"


